### ISSUE TITLE
How to use with remote data

### ISSUE THREAD

**Issue by heromiyo** [nihk/exo-viewpager-fun#2]
Hi, asking for help on how to use with remote data 

I have a video app where a user posts a video to firebase realtime db and then i have to fetch and display the videos 

My repository for fetching videos 

  override suspend fun getVidoRandVideos(): Flow<FlowDataState<List<RemoteVideo>>> {
        return realFire.getReference(firePath.getAllVideosPath()).also { it.keepSynced(true) }
            .limitToFirst(12)
            .awaitSingleValueEventList()

    }

// getting the list of videos 

 override fun videoData(): Flow<List<RemoteVideo>> {
        return flowOf(videoData)
    }
    override suspend fun  getData() {
        getVidoRandVideos().collect {
            when (it) {
                is FlowDataState.Success -> {
                    videoData = it.data
                }
                is FlowDataState.Error -> {

                }
            }
        }
    }

How can use the VideoDataRepositories to fetch this data instead of hard coding it ?

interface VideoDataRepository {
    fun videoData(): Flow<List<RemoteVideo>>
}

class AssetVideoDataRepository : VideoDataRepository {
    override fun videoData(): Flow<List<RemoteVideo>> {
        return flowOf(videoData)
    }
    companion object {

// DONT WANT TO HARD CODE BUT SHOULD FETCH FROM REMOTE DATASOURCE AND ALSO BE ABLE TO OBSERVE IN THE VIEWMODEL
        private val videoData = listOf(
            RemoteVideo("https://firebasestorage.googleapis.com/v0/b96c-5868-4a4b-a48e-c8e9f3dd7b13?alt=media&token=14a443fd-75e9-42a8-880e-5b8a6df5e0a2", description="#nice the best" , tags= mapOf(), duration=831, videoId="2c7effa1-319e-4073-948f-20543c60503b", dateCreated=1628120270055, likes=0, views=0, authorUid="loUXJN7p4WbzYke94eiRq7QK64Y2", totalCommentsSize=0),
            RemoteVideo("https://firebasestorage.googleapis.com/v0/boUXJN7p4WbzYke94eiRq7QK64Y2%2F699e8432-257a-4663-877e-9b29807d564f?alt=media&token=e5042726-2ec5-4d42-b8e4-23cf5169b780", description="#nice the best" , tags= mapOf(), duration=831, videoId="2c7effa1-319e-4073-948f-20543c60503b", dateCreated=1628120270055, likes=0, views=0, authorUid="loUXJN7p4WbzYke94eiRq7QK64Y2", totalCommentsSize=0),
            RemoteVideo("https://-3af2-44ed-8d1a-8b09134aaf07", description="#nice the best" , tags= mapOf(), duration=831, videoId="2c7effa1-319e-4073-948f-20543c60503b", dateCreated=1628120270055, likes=0, views=0, authorUid="loUXJN7p4WbzYke94eiRq7QK64Y2", totalCommentsSize=0),
        )
    }
}

**Comment by nihk** [comment]
Hey @heromiyo, great question.  In this project, all `MainViewModel` cares about is the `VideoDataRepository` interface - it doesn't know anything about how it ultimately gets the `List<VideoData>`. That means you can pass in any custom implementation of `VideoDataRepository` to the ViewModel. For example, you could create a `FirebaseVideoDataRepository` implementation which uses Firebase to acquire the list of videos. `VideoDataRepository` has the one function which returns a `Flow<List<VideoData>>`; that represents a stream of data that could be anything on any thread. 

In your case with Firebase you'll want to get a Flow of your relevant Firebase objects then map them to a `List<VideoData>`.  I'm not familiar with the Firebase APIs, but here's the basic idea with some contrived classes:

```
class FirebaseVideoDataRepository(private val firebase: Firebase) : VideoDataRepository {
    override fun videoData(): Flow<List<VideoData>> {
        return firebase.getAllVideos()
            .map { videos -> videos.toVideoData() }
    }
    
    private fun List<FirebaseVideo>.toVideoData(): List<VideoData> {
        return map { firebaseVideo ->  VideoData(mediaUri = firebaseVideo.url) }
    }
}

interface Firebase {
    fun getAllVideos(): Flow<List<FirebaseVideo>>
}

data class FirebaseVideo(val url: String)
```

You could change the return type of VideoDataRepository's function to have some wrapper representing state, too. E.g. `fun videoData(): Flow<MyState<List<VideoData>>>`. That will facilitate the Success/Error states in your example.

Note that the current state of the app in this repository won't show image previews of remote videos (only local videos). This can be achieved by simply adding a new field to the `VideoData` object representing the image URL of a frame preview, then using it in the RecyclerView.ViewHolder. I'll check in a commit later to make that more clear.

**Comment by heromiyo** [comment]
Hey @nihk Thanks, i followed the steps and managed to fetch the videos, working on exoplayer caching (Preloading?/PreCaching?) .
Thanks for your help

**Comment by nikolamakin** [comment]
hi, Have you solved it
Can I post part of the code of the response
